services:
  proxy:
    image: nginx:1.21.6-alpine
    container_name: proxy
    volumes:
      - ./proxy:/etc/nginx/templates
    ports:
      - "17778:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal_net
  
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - internal_net

  frontend:
    image: odiakun/frontend:latest
    depends_on:
      - proxy
    env_file:
      - variables-deploy.env
    networks:
      - internal_net

  entrance:
    image: odiakun/entrance:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - variables-deploy.env
    networks:
      - internal_net

  chat:
    image: odiakun/chat:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      - variables-deploy.env
    networks:
      - internal_net


  login:
    image: odiakun/login:latest
    depends_on:
      - postgres
    env_file:
      - variables-deploy.env
    networks:
      - internal_net

networks:
      mongo_net:
              external: true
              name: admin-mongodb_default
      postgres_net:
              external: true
              name: admin-postgres_default
      internal_net:
              name: HPDS_177788_internal
              driver: overlay
